---
version: "3"
services:
  front:
    image: node:11.10.0
    hostname: front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/etc/front
    working_dir: /etc/front
    # command: "npm run demo"
    command: "sh -c 'while sleep 3600; do :; done'"
